// Precompiles every EJS template in views/ into plain JavaScript functions.
//
// Cloudflare Workers forbid runtime code generation (eval / new Function), which is how
// EJS normally compiles templates. Instead we let EJS generate each template's source
// at build time and write it into src/generated/views.js as ordinary functions.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ejs from 'ejs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const viewsDir = path.join(root, 'views');
const outFile = path.join(root, 'src', 'generated', 'views.js');

const INTERNAL = new Set(['locals', 'escapeFn', 'include', '__output', '__append']);

function isBindable(name) {
  if (INTERNAL.has(name) || name in globalThis) return false; // never shadow globals like JSON or Number
  try {
    new Function(`let ${name};`); // rejects reserved words (if, class, true, …)
    return true;
  } catch {
    return false;
  }
}

/**
 * Names a template may read from its locals: every identifier used inside its <% %> tags,
 * minus JS keywords, globals and variables the template declares itself. Names that turn
 * out to be properties or arrow-function parameters are harmless (they're just undefined
 * or shadowed), and this way a newly used local can never be forgotten.
 */
function localNames(src) {
  const code = [...src.matchAll(/<%[_=-]?([\s\S]*?)[_-]?%>/g)].map((m) => m[1]).join('\n');
  const declared = new Set([...code.matchAll(/\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)/g)].map((m) => m[1]));
  const names = new Set(code.match(/[A-Za-z_$][\w$]*/g) || []);
  return [...names].filter((n) => !declared.has(n) && isBindable(n)).sort();
}

function listTemplates(dir, prefix = '') {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) return listTemplates(path.join(dir, entry.name), rel);
    return entry.name.endsWith('.ejs') ? [rel.replace(/\.ejs$/, '')] : [];
  });
}

const entries = listTemplates(viewsDir)
  .sort()
  .map((name) => {
    const file = path.join(viewsDir, `${name}.ejs`);
    const src = fs.readFileSync(file, 'utf8');
    const template = new ejs.Template(src, {
      filename: file,
      strict: true,
      compileDebug: false,
      _with: false,
      localsName: 'locals',
    });
    template.generateSource();
    return `  ${JSON.stringify(name)}: function (locals, escapeFn, include) {
    const { ${localNames(src).join(', ')} } = locals;
    let __output = '';
    const __append = (s) => { if (s !== undefined && s !== null) __output += s; };
${template.source}
    return __output;
  },`;
  });

const output = `// Generated by scripts/build-views.mjs — do not edit. Run \`npm run build\` after changing views/.
/* eslint-disable */
export default {
${entries.join('\n')}
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, output);
console.log(`Compiled ${entries.length} templates -> ${path.relative(root, outFile)}`);
